version: '3'

services:

  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: "always"
    command: "--api --docker"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.ui.frontend.rule=Host:traefik"
      - "traefik.ui.port=8080"
    networks:
      local:
        aliases:
          - "megogo.local"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    labels:
      - "traefik.ui.frontend.rule=Host:elasticsearch.filatium.com"
      - "traefik.ui.port=9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - local

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=123"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      local:
        aliases:
          - "mysql"

  app:
    image: app
    container_name: app
    labels:
      - "traefik.ui.frontend.rule=Host:filatium.com"
      - "traefik.ui.port=8081"
    networks:
      - local
volumes:
  esdata:
    driver: local
  mysqldata:
    driver: local

networks:
  local: